[project]
name = "parley-tap-prompt-injection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mistralai>=1.9.3",
    "openai>=1.98.0",
    "together>=1.5.21",
]
